<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Alegra test 1');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl().'/js/ext-all.js' ?>"</script>
    <script type="text/javascript" src="<?php echo $this->baseUrl().'/js/ext-lang-es.js' ?>"></script>
    <link type="image/x-icon" rel="shortcut icon" href="<?php echo $this->baseUrl().'/images/favicon.ico' ?>"/>
    <link rel="stylesheet" type="text/css" href="https://cdn1.alegra.com/public/877dae0d3d54df111117a9ded35b92ba/compressed/styles-min.css" />
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/ext-theme-gray-all2.css'); ?>
</head>
<script type="text/javascript">
            
                        //Fix updateGroupsOnUpdate
                        //https://www.sencha.com/forum/showthread.php?301214-ExtJS4-2-3-Ext-data-Store-updateGroupsOnUpdate-fails-when-filtered-away-row-modified
                        Ext.override(Ext.data.Store, {
                                updateGroupsOnUpdate: function(record, modifiedFieldNames){
                                    var me = this,
                                    groupField = me.getGroupField(),
                                    groupName = me.getGroupString(record),
                                    groups = me.groups,
                                    len, i, items, group;

                                    if (modifiedFieldNames && Ext.Array.contains(modifiedFieldNames, groupField)) {

                                    // Sorting is remote for buffered stores, we cannot update a field which is a sort key
                                    if (me.buffered) {
                                        Ext.Error.raise({
                                        msg: 'Cannot move records between groups in a buffered store record'
                                        });
                                    }

                                    // First find the old group and remove the record
                                    items = groups.items;
                                    for (i = 0, len = items.length; i < len; ++i) {
                                        group = items[i];
                                        if (group.contains(record)) {
                                        group.remove(record);
                                        break;
                                        }
                                    }
                                    group = groups.getByKey(groupName);
                                    if (!group) {
                                    group = groups.add(new Ext.data.Group({
                                    key: groupName,
                                    store: me
                                    }));
                                    }
                                    group.add(record);

                                    // At this point we know that we're sorted, so re-insert the record.
                                    // Without adding to the "removed" list or firing events!
                                    me.data.remove(record);
                                    me.data.insert(me.data.findInsertionIndex(record, me.generateComparator()), record);

                                    } else {
                                    // some other field changed, just mark the group as dirty
                                        group = groups.getByKey(groupName);
                                        if (group) {
                                            group.setDirty();
                                        }
                                    }
                                }
                        });
                        /*End fix***********************************/
 </script>
<body>
 <!--<h1><?php /*echo $this->escape($this->title);*/ ?></h1>-->
 <?php echo $this->layout()->content; ?>
</body>
</html>